### ISSUE TITLE
Internet Connectivity Flags

### ISSUE THREAD

**Issue by n2mh** [aredn/aredn_ar71xx#223] opened 2018-10-13 15:38 UTC
There's been some discussion lately about various services in a node that require Internet connectivity in order to function. Perhaps it's time for a node to be aware internally if it has Internet connectivity and how? These flags would be used by all services requiring Internet connectivity and control whether they operate at all. This might fix some timeout issues being reported and overall provide a cleaner operating node.

* DNS
* WAN Gateway (Issue 200)
* Mesh Gateway (Issue 214)
* UI Delay (Issue 222)
* NTP (inform sysop that NTP souce must now be on net)
* Others ?

**Comment by ae6xe** [comment] 2018-10-13 18:54
I think there are 2 categories here:

1) what happens with a feature when the internet is intermittent --   As end users we expect the internet to be there, but if it is not then failures may occur.  Remaining and available mesh node features should not hinder the end user and still function.

2) It is problematic when the configuration settings do not account for a desire to not access the internet or there is no internet gateway on the mesh by design.     I want to turn these features off and/or use mesh equivalent services that may be stood up.  

200 , 214 are category #1 
222, DNS, and NTP are category #2 

This thread isn't tracking any specific issue that we can implement and close out on it's own.  It would be best to create new issues for DNS or NTP that describe the problem (failure or lacking capability), that we can bring to a close.    For example, with NTP, there might be an enhancement request for settings to enable a user definable NTP server search list including  mesh and internet IP addresses, or turn off altogether.

If it's OK with everyone, let's close this thread and move dialog to the specific issues that can be closed out on their own.

**Closed** 2018-10-16 02:58 UTC
Labels: bug
