### ISSUE TITLE
vtun package is missing

### ISSUE THREAD

**Issue by dman776** [aredn/aredn_ar71xx#56] opened 2018-07-12 19:07 UTC
build 36 does not contain vtun package

**Comment by ae6xe** [comment] 2018-07-12 19:18
This latest branch of openwrt does not by default build all the packages.  We need to explicit add a config entry for each package that needs to be built.  The issue is beyond vtun.   Current list of used add-on packages to include:
1) vtun
2) hamchat
3) tcpdump

What else?

**Comment by dman776** [comment] 2018-07-12 19:49
i need to lookup all the dependencies for vtun
remove hamchat
add meshchat
add iperf

**Comment by Orv** [comment] 2018-07-12 22:10
add iperfspeed!

**Comment by ae6xe** [comment] 2018-07-12 22:29
by adding a package to be built in the config file definition, e.g. vtun, the dependent packages will automatically be built and do not need separately added.   We just need top level package list to build.

meshchat is 3rd party contributed and distributed?

**Comment by ae6xe** [comment] 2018-07-12 22:30
iperfspeed is 3rd part contributed too, as I recall, but we can talk to the creator...

**Comment by dman776** [comment] 2018-07-12 22:31
yes.  I sent a note to Trevor asking if github was current.  https://github.com/tpaskett/meshchat and https://github.com/tpaskett/iperfspeed

**Comment by ae6xe** [comment] 2018-07-12 22:45
Need to investigate the options, this isn't an issue of how to include in the AREDN compile process to install the meshchat and iperfspeed packages.  It's a different problem to solve of how to reference and/or include these 3rd party compiled packages into the release (or how a live node can automatically refresh and find this package for download directly from the 3rd party).    Would help if we make this a different issue to track what to do on this.

**Comment by dman776** [comment] 2018-07-12 22:59
Agree.  Let’s make it a new issue (feature request)

Thanks,
Darryl

**Comment by ae6xe** [comment] 2018-07-14 15:17
vtun is now compiling in, but is not installed in default images per design with 7c163de .
tcpdump was already distributed in the image.
iperf package is already built. 

That completes the ideas we had on this issue, so I'll close this issue.

**Closed by ae6xe** 2018-07-14 15:17 UTC
Labels: bug
